### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lllh9** [JRL-CARI-CNR-UNIBS/JRL-CARI_motion_planning#2]
Errors     << cnr_param:cmake /home/c/pathplanning/logs/cnr_param/build.cmake.002.log
CMake Error at /home/c/pathplanning/src/cnr_common/cnr_param/cmake/cnrDependencies.cmake:53 (message):
  cnr_yaml not found!
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)

cd /home/c/pathplanning/build/cnr_param; catkin build --get-env cnr_param | catkin env -si  /usr/bin/cmake /home/c/pathplanning/src/cnr_common/cnr_param --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/c/pathplanning/devel/.private/cnr_param -DCMAKE_INSTALL_PREFIX=/home/c/pathplanning/install; cd -

...............................................................................
Failed     << cnr_param:cmake                           [ Exited with code 1 ] 
Failed    <<< cnr_param                                 [ 0.1 seconds ]        
Abandoned <<< cnr_scene_manager                         [ Depends on failed job cnr_param ]
Abandoned <<< graph_core                                [ Depends on failed job cnr_param ]
Abandoned <<< graph_display                             [ Depends on failed job cnr_param ]
Abandoned <<< moveit_collision_checker                  [ Depends on failed job cnr_param ]
Abandoned <<< graph_ros_tests                           [ Depends on failed job cnr_param ]
                                                                               
[build] Successful packages:                                                   
                                                                               
 [Successful] cartesian_description      [Successful] cartesian_moveit_config   
 [Successful] cnr_class_loader           [Successful] cnr_logger                
 [Successful] cnr_scene_manager_msgs     [Successful] cnr_tf_named_object_loader
 [Successful] cnr_yaml                   [Successful] uav_moveit_config         
                                                                               
[build] Abandoned packages:                                                    
                                                                               
 [ Abandoned] cnr_scene_manager          [ Abandoned] graph_core                
 [ Abandoned] graph_display              [ Abandoned] graph_ros_tests           
 [ Abandoned] moveit_collision_checker                                         
                                                                               
[build] Failed packages:                                                       
                                                                               
 [    Failed] cnr_param                                                        
                                                                               
[build] Summary: 8 of 14 packages succeeded.                                   
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 5 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 4.1 seconds total.

**Comment by CesareTonola** [comment]
That seems a bug of [cnr_param](https://github.com/CNR-STIIMA-IRAS/cnr_param) or [cnr_yaml](https://github.com/CNR-STIIMA-IRAS/cnr_yaml). Please, open an issue on one of those repos.

**Comment by CesareTonola** [comment]
Should be fixed now
